-- 코드를 입력하세요
SELECT MODIFIED.ANIMAL_TYPE, count(MODIFIED.ANIMAL_TYPE)
FROM ANIMAL_INS ORIGIN
LEFT JOIN (
    SELECT ANIMAL_ID, ANIMAL_TYPE
    FROM ANIMAL_INS
    WHERE ANIMAL_TYPE = 'Cat' OR ANIMAL_TYPE = 'Dog') MODIFIED
ON ORIGIN.ANIMAL_ID = MODIFIED.ANIMAL_ID
GROUP BY MODIFIED.ANIMAL_TYPE
ORDER BY MODIFIED.ANIMAL_TYPE