-- 코드를 입력하세요
SELECT M.CART_ID
FROM (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME IN ('Milk')
) AS M
INNER JOIN (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME IN ('Yogurt')
) AS Y
WHERE M.CART_ID = Y.CART_ID
ORDER BY M.CART_ID