-- 코드를 입력하세요
SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME
FROM ANIMAL_INS
LEFT JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
ORDER BY UNIX_TIMESTAMP(ANIMAL_OUTS.DATETIME) - UNIX_TIMESTAMP(ANIMAL_INS.DATETIME) DESC
LIMIT 2