-- 코드를 입력하세요
SELECT
    DISTINCT C.CAR_ID,
    C.CAR_TYPE,
    ROUND(DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    USING(CAR_ID)
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
    USING(CAR_TYPE)
WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND C.CAR_ID NOT IN (
            SELECT CAR_ID 
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
            WHERE START_DATE <= '2022-11-01' AND END_DATE >= '2022-11-01'
    )
    AND DURATION_TYPE = '30일 이상'
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC,
            C.CAR_TYPE ASC,
            C.CAR_ID DESC