-- 코드를 입력하세요
SELECT MJ.FLAVOR
FROM (
    SELECT J.FLAVOR, sum(J.TOTAL_ORDER) AS sumJ
    FROM JULY AS J
    GROUP BY J.FLAVOR ) AS MJ
INNER JOIN (
    SELECT F.FLAVOR, sum(F.TOTAL_ORDER) AS sumF
    FROM FIRST_HALF AS F
    GROUP BY F.FLAVOR ) AS MF
ON MJ.FLAVOR = MF.FLAVOR
ORDER BY MJ.sumJ + MF.sumF DESC
LIMIT 3