-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, sum(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER U
LEFT JOIN (
    SELECT WRITER_ID, PRICE
    FROM USED_GOODS_BOARD
    WHERE STATUS IN ('DONE')) B
ON U.USER_ID = B.WRITER_ID
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES