-- 코드를 입력하세요
SELECT PRODUCT_CODE, PRICE * sum(SALES_AMOUNT) AS 'SALES'
FROM PRODUCT
LEFT JOIN OFFLINE_SALE
ON PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY PRICE * sum(SALES_AMOUNT) DESC, PRODUCT_CODE