-- 코드를 입력하세요
SELECT T.ORDER_ID, T.PRODUCT_ID, date_format(T.OUT_DATE, '%Y-%m-%d'),
CASE
    WHEN T.OUT_DATE IS NULL THEN '출고미정'
    WHEN DATEDIFF(T.OUT_DATE, '2022-05-01') <= 0 THEN '출고완료'
    ELSE '출고대기'
END '출고여부'
FROM FOOD_ORDER T
ORDER BY T.ORDER_ID