SELECT P1.MEMBER_NAME, R1.REVIEW_TEXT, DATE_FORMAT(R1.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE P1
    LEFT JOIN REST_REVIEW R1
    ON P1.MEMBER_ID = R1.MEMBER_ID
WHERE P1.MEMBER_ID IN (
    SELECT P2.MEMBER_ID
    FROM MEMBER_PROFILE P2
        LEFT JOIN REST_REVIEW R2
        ON P2.MEMBER_ID = R2.MEMBER_ID
    GROUP BY P2.MEMBER_ID
    HAVING COUNT(P2.MEMBER_ID) = (
        SELECT COUNT(P3.MEMBER_ID)
        FROM MEMBER_PROFILE P3
            LEFT JOIN REST_REVIEW R3
            ON P3.MEMBER_ID = R3.MEMBER_ID
        GROUP BY P3.MEMBER_ID
        ORDER BY COUNT(P3.MEMBER_ID) DESC
        LIMIT 1
    )
)
ORDER BY REVIEW_DATE, REVIEW_TEXT

