-- 코드를 입력하세요
SELECT P.*
FROM PLACES P
LEFT JOIN (
    SELECT HOST_ID
    FROM PLACES 
    GROUP BY HOST_ID
    HAVING count(HOST_ID) > 1 ) H
ON P.HOST_ID = H.HOST_ID
WHERE H.HOST_ID IS NOT NULL
ORDER BY P.ID